# Generated by Django 4.0.1 on 2022-01-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completedDTF',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='createdDTF',
            field=models.DateField(auto_now_add=True),
        ),
    ]
